<?php
/**----------------------------------------------------------------------
 * OpenCenter V3
 * Copyright 2014-2018 http://www.ocenter.cn All rights reserved.
 * ----------------------------------------------------------------------
 * Author: wdx(wdx@ourstu.com)
 * Date: 2018/9/28
 * Time: 14:39
 * ----------------------------------------------------------------------
 */

namespace app\admin\controller;

use app\admin\validate\UserRole;
use app\admin\validate\UserRule;
use app\admin\model\UserCoin;
use app\admin\model\UserReal;
use app\admin\model\UserRequire;
use app\admin\model\UserBank;
use app\admin\model\AdminLog;
use app\admin\model\User AS AdminUser;
use app\admin\model\UserCoinAddress;
use app\common\component\Openim;
use think\Db;
use app\admin\model\User as UserModel;
use app\admin\model\Contact;

/**
 * Class User
 * 用户控制器类
 * @package app\admin\controller
 */
class Apply extends Base
{
    protected $apple;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->apple = model('admin/Apple');
    }

    /**
     * 申请列表
     * @return mixed|\think\response\Json
     * @author:wdx(wdx@ourstu.com)
     */
    public function lst()
    {
        if ($this->request->isAjax()) {
            $page = input('get.page/d', 1);
            $limit = input('get.limit/d', 20);
            $houseName = request()->param('house_name');
            $map = [];
            $where = [];
            if($houseName != "" && $houseName != null)
            {
                $map[] = ["house_name","like","%" . $houseName . "%"];
                $appleDeatilsId = Db::name("apple_details")->where($map)->order("created_at desc")->value("apple_id");
                if(isset($appleDeatilsId))
                {
                    $where["id"] = $appleDeatilsId;
                }
            }
            $userList = $this->apple->where($where)->page($page, $limit)->order('id desc')->select()->toArray();
            $count = $this->apple->where($where)->count();
            for ($a=0;$a<count($userList);$a++) {
                $userList[$a]['house_name'] = Db::name("apple_details")->where(['apple_id'=>$userList[$a]['id']])->order("created_at desc")->value("house_name");
                if($userList[$a]['status'] == 0)
                {
                    $userList[$a]['status'] = 'apply';
                } elseif($userList[$a]['status'] == 1){
                    $userList[$a]['status'] = '审核中';
                } elseif($userList[$a]['status'] == 2){
                    $userList[$a]['status'] = '已审核';
                } else {
                    $userList[$a]['status'] = '已驳回';
                }
                $userList[$a]['created_at'] = date("Y-m-d H:i:s",$userList[$a]['created_at']);
                $userList[$a]['username'] = Db::name('user')->where(['id'=>$userList[$a]['user_id']])->value("username");
                if($userList[$a]['process_type'] == 0)
                {
                    $userList[$a]['process_type'] = "常规流程";
                } else {
                    $userList[$a]['process_type'] = "简易流程";
                }
                if($userList[$a]['is_soft_first'] == 0)
                {
                    $userList[$a]['is_soft_first'] = "不需要";
                } else {
                    $userList[$a]['is_soft_first'] = "需要";
                }
                if($userList[$a]['is_public_rental'] == 0)
                {
                    $userList[$a]['is_public_rental'] = "否";
                } else {
                    $userList[$a]['is_public_rental'] = "是";
                }
            }

            $data = [
                'code' => 0,
                'msg' => '数据返回成功',
                'count' => $count,
                'data' => $userList
            ];
            AdminLog::setTitle('获取租赁申请列表');
            return json($data);
        }

        AdminLog::setTitle('申请列表');
        return $this->fetch();
    }

    //租赁申请详情
    public function userAccount()
    {
        $id = input('get.id/d', 0);
        $demondInfo = Db::name('apple')
            ->where(['a.id'=>$id])
            ->alias('a')
            ->order('d.created_at desc')
            ->join('apple_details d','a.id = d.apple_id')
            ->field("d.*,a.created_at,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
            ->find();

        $this->assign([
            'demondInfo' => $demondInfo
        ]);
        return $this->fetch();
    }
}