<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/23
 * Time: 16:16
 */
namespace app\admin\controller;

class Bank extends Base
{

    protected $bank;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->bank = model('admin/Bank');
    }

    /*
     * 银行
     * */
    public function lst(){
        if ($this->request->isAjax()) {
            $page = input('get.page/d', 1);
            $limit = input('get.limit/d', 20);
            $map = array();
            $zfList = $this->bank
                ->where($map)
                ->order('list_order asc')
                ->page($page, $limit)
                ->select();

            for ($a=0;$a<count($zfList);$a++)
            {
                if($zfList[$a]['status'] == 0)
                {
                    $zfList[$a]['status'] = '不可用';
                } else {
                    $zfList[$a]['status'] = '可用';
                }
            }

            $count = $this->bank->where($map)->count();
            $data = [
                'code' => 0,
                'msg' => '数据返回成功',
                'count' => $count,
                'data' => $zfList
            ];
            return json($data);
        }
        return $this->fetch();
    }

    /*
     * 添加或编辑
     * */
    public function bankForm(){
        if ($this->request->isPost()) {
            $data = input('');
            $title = $data['id'] ? '编辑' : '新增';
            if(isset($data['status']))
            {
                $data['status'] = 1;
            } else {
                $data['status'] = 0;
            }

            if (!empty($data['id'])) {     //编辑
                $rs = $this->bank->update($data);
            }else{
                $rs = $this->bank->insert($data);
            }
            if ($rs) {
                $this->success($title . '成功');
            } else {
                $this->error($title . '失败');
            }
        } else {
            $aid = input('get.aid/d', 0);
            $info = $this->bank->where('id='.$aid)->find($aid);
            $this->assign('info', $info);
            return $this->fetch();
        }
    }
}