<?php
namespace app\admin\controller;
use think\response\Json;
use think\Db;

class Reply extends Base
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->reply = Db::table('ecshecom_portal_reply');
    }
    //列表
    public function reply()
    {
        if ($this->request->isAjax()) {
            $page = input('get.page/d', 1);
            $limit = input('get.limit/d', 20);
            $map[]=['type','eq',1];
            $map[]=['status','neq',4];
            $zfList = $this->reply
                ->where($map)
                ->page($page, $limit)
                ->order('create_at desc')
                ->select();
            foreach($zfList as $key=>$val){
                switch ($zfList[$key]['status']) {
                    case '0':
                        $zfList[$key]['status']="未发布";
                        break;
                    
                    case '1':
                        $zfList[$key]['status']="已发布";
                        break;
                }
                $zfList[$key]['create_at']=date('Y-m-d H:i:s',$zfList[$key]['create_at']);
            }
            $count = $this->reply->where($map)->count();
            $data = [
                'code' => 0,
                'msg' => '数据返回成功',
                'count' => $count,
                'data' => $zfList
            ];
            return json($data);
        }
        return $this->fetch('reply_list');
    }
    public function replyForm(){
        if ($this->request->isPost()) {
            $data = input('data/a', []);
            $title = $data['id'] ? '编辑' : '新增';
            if($data['post_status']==1){
                $data['published_time']=time();
            }else{
                $data['published_time']='';
            }
            if (!empty($data['id'])) {     //编辑
                $rs = $this->reply->update($data);
            }else{
                $rs = $this->reply->insert($data);
            }
            if ($rs) {
                $this->success($title . '成功');
            } else {
                $this->error($title . '失败');
            }
        } else {
            $aid = input('get.aid/d', 0);
            $info = $this->reply->where('id='.$aid)->find($aid);
            $this->assign('info', $info);
            return $this->fetch('reply_form');
        }
    }
    public function delReply()
    {
        $ids = array_unique(input('post.id/a', []));

        foreach ($ids as $val) {
            $rs = Db::table('ecshecom_portal_reply')->where('id', $val)->setField(['status'=>4]);
        }
        unset($val);
        $this->success('删除成功');
    }
}
