<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/23
 * Time: 16:18
 */

namespace app\admin\controller;
use think\response\Json;
use think\Db;


/**
 * 快捷入口
 * Class Entrance
 * @package app\admin\controller
 */
class Sms extends Base
{
    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->sms = Db::table('ecshecom_sms_logs');
    }
    //列表
    public function index()
    {
        if ($this->request->isAjax()) {
            $page = input('get.page/d', 1);
            $limit = input('get.limit/d', 20);
            $map[] = ['id', '<>', 0];
            $map[] = ['is_show', '=', 1];
            $List = $this->sms
                ->where($map)
                ->page($page, $limit)
                ->order('id desc')
                ->select();
            foreach($List as $key=>$val){
                $List[$key]['time']=date('Y-m-d H:i:s',$List[$key]['time']);
            }
            $count = $this->sms->where($map)->count();

            $data = [
                'code' => 0,
                'msg' => '数据返回成功',
                'count' => $count,
                'data' => $List
            ];
            return json($data);
        }
        return $this->fetch('sms_list');
    }
    public function delSms()
    {
        $ids = array_unique(input('post.id/a', []));
        foreach ($ids as $val) {
            $rs = Db::table('ecshecom_sms_logs')->where('id', $val)->delete();
        }
        unset($val);
        $this->success('刪除成功');
    }

}