<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/23
 * Time: 16:18
 */

namespace app\admin\controller;
use think\response\Json;
use \think\facade\Lang;
use think\Db;


/**
 * 快捷入口
 * Class Entrance
 * @package app\admin\controller
 */
class Usernotice extends Base
{
    /**
     *
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->notice = Db::table('ecshecom_user_notice');
        Lang::load( '../application/common/lang/zh-tw.php');
    }
    //列表
    public function index()
    {
        if ($this->request->isAjax()) {
            $page = input('get.page/d', 1);
            $limit = input('get.limit/d', 20);
            $List = $this->notice
                ->alias('n')
                ->join('user u','n.user_id = u.id')
                ->field('n.*,u.username')
                ->page($page, $limit)
                ->order('n.created_at desc')
                ->select();
            foreach($List as $key=>$val){
                $List[$key]['created_at']=date('Y-m-d H:i:s',$List[$key]['created_at']);
                $List[$key]['description'] = lang($List[$key]['description']);
            }
            $count = $this->notice->count();

            $data = [
                'code' => 0,
                'msg' => '数据返回成功',
                'count' => $count,
                'data' => $List
            ];
            return json($data);
        }
        return $this->fetch('sms_list');
    }
    public function delSms()
    {
        $ids = array_unique(input('post.id/a', []));
        foreach ($ids as $val) {
            $rs = Db::table('ecshecom_user_notice')->where('id', $val)->delete();
        }
        unset($val);
        $this->success('刪除成功');
    }

}