<?php


namespace app\index\controller;

use app\index\model\Coin;
use think\Db;

class Bid extends Base
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        return $this->fetch();
    }

    public function saveView($bidId = 0)
    {

        /**
         * 只有村企业可提交申请
         * */
        if ($this->roleId == 0) {
            $demondInfo = $this->getBidDetail($bidId);

            $this->assign([
                'demondInfo' => $demondInfo,
            ]);
            if (isMobile()) {
                return $this->fetch("view_mobile_bid_save");
            } else {
                return $this->fetch("view_bid_save");
            }
        }

        return;
    }

    public function saveBid()
    {
        foreach ($this->params as $k => $v) {
            if ($k != 'bid_id' && $k != 'other_require' && $k != 'file1'&& $k != 'file2'&& $k != 'file3'&& $k != 'file4'&& $k != 'file5'&&$k != 'file_1'&& $k != 'file_2'&& $k != 'file_3'&& $k != 'file_4') {
                if ($v == '') {
                    $this->apiReturn('200', "请将信息填写完整！", []);
                }
            }
        }

        //时间戳转时间
        $this->params['enrol_start_time'] = strtotime($this->params['enrol_start_time']);
        $this->params['enrol_end_time'] = strtotime($this->params['enrol_end_time']);
        $this->params['saudit_end_time'] = strtotime($this->params['saudit_end_time']);
        $this->params['bid_qual_etime'] = strtotime($this->params['bid_qual_etime']);
        $this->params['auction_etime'] = strtotime($this->params['auction_etime']);


        if ($this->params['bid_id'] == '') //新增申请
        {
            $bidData = [
                'creator_id' => $this->userId,
                'status' => 1,
                'rent_type' => $this->params['rent_type'],
                'enrol_method' => $this->params['enrol_method'],
                'enrol_start_time' => $this->params['enrol_start_time'],
                'enrol_end_time' => $this->params['enrol_end_time'],
                'site_audit_address' => $this->params['site_audit_address'],
                'site_audit_material' => $this->params['site_audit_material'],
                'saudit_end_time' => $this->params['saudit_end_time'],
                'bid_qual_etime' => $this->params['bid_qual_etime'],
                'auction_etime' => $this->params['auction_etime'],
                'rent_saudit_method' => $this->params['rent_saudit_method'],
                'rent_name' => $this->params['rent_name'],
                'rent_address' => $this->params['rent_address'],
                'rent_house' => $this->params['rent_house'],
                'rent_area' => $this->params['rent_area'],
                'rental_properties' => $this->params['rental_properties'],
                'rental_cert' => $this->params['rental_cert'],
                'rent_contact_name' => $this->params['rent_contact_name'],
                'rent_contact_phone' => $this->params['rent_contact_phone'],
                'qual_audit_method' => $this->params['qual_audit_method'],
                'qual_require' => $this->params['qual_require'],
                'manage_ability' => $this->params['manage_ability'],
                'asset_require' => $this->params['asset_require'],
                'priority_qual' => $this->params['priority_qual'],
                'industry_require' => $this->params['industry_require'],
                'bid_security' => $this->params['bid_security'],
                'other_require' => $this->params['other_require'],
                'bid_low_price' => $this->params['bid_low_price'],
                'bid_increase' => $this->params['bid_increase'],
                'lease_period' => $this->params['lease_period'],
                'lease_time' => $this->params['lease_time'],
                'rent_free_period' => $this->params['rent_free_period'],
                'lease_calculat_stime' => $this->params['lease_calculat_stime'],
                'business_purpose' => $this->params['business_purpose'],
                'tax_convention' => $this->params['tax_convention'],
            ];

//            if($this->params['bidder_type']==1){  //企业
//                $bidData['file1'] = $this->params['file1'];
//                $bidData['file2'] = $this->params['file2'];
//                $bidData['file3'] = $this->params['file3'];
//                $bidData['file4'] = $this->params['file4'];
//                $bidData['file5'] = $this->params['file5'];
//            }else{    //个人
//                $bidData['file1'] = $this->params['file_1'];
//                $bidData['file2'] = $this->params['file_2'];
//                $bidData['file3'] = $this->params['file_3'];
//                $bidData['file4'] = $this->params['file_4'];
//                $bidData['file5'] = "";
//            }
            $bidId = Db::name("bid")->insertGetId($bidData);

            if ($bidId) {
                //添加通知
                addNotice("审核单已提交,点击查看!", $this->userId, $bidId);
                $this->apiReturn('100', "已提交！", []);
            }
            $this->apiReturn('200', "您的申请提交失败，请重新提交！！", []);
        } else { //修改申请
            // TODO 修改入口
        }

    }

    /**
     * 查看需求列表
     */
    public function bidList($status = 0)
    {
        if ($this->roleId == 0) //村企业
        {
            $where['a.creator_id'] = $this->userId;
            //当前用户发布的申请
            $demondInfos = Db::name('bid')
                ->alias('a')
                ->where($where)
                ->order('a.created_at desc')
                ->field("a.*")
                ->paginate(40, false, ['query' => request()->param()]);
            $page = $demondInfos->render();
        } else if (in_array($this->roleId, [1, 3, 8])) {
            $demondInfos = Db::name('bid')
                ->alias('a')
                ->order('a.created_at desc')
                ->field("a.*")
                ->paginate(40, false, ['query' => request()->param()]);
            $page = $demondInfos->render();
        } else {
            return;
        }
		foreach($demondInfos as &$v){
        	if($v['examine_type']==0){
            	$v['examine_type'] = '预审中';
            }else if($v['examine_type']==1){
            	$v['examine_type'] = '再次审核';
            }else if ($v['examine_type']==2){
            	$v['examine_type'] = '终审中';
            }
        }//echo '<pre>';var_dump($demondInfos);die;
        $this->assign([
            'demondInfos' => $demondInfos,
            'page' => $page,
            'status' => $status,
            'role' => $this->roleId,
            'userId' => $this->userId,
        ]);

        if (isMobile()) {
            return $this->fetch("show_mobile_bid_list");
        } else {
            return $this->fetch("show_bid_list");
        }

    }

    public function viewBid($bidId = 0)
    {
        $demondInfo = $this->getBidDetail($bidId);//var_dump($demondInfo);die;
        //审核情况
        $examineInfo = Db::name("bid_examine")->where(['bid_id' => $bidId])->order("created_at desc")->find();
        $examTitle = $demondInfo['examine_type'] == 1 ? "再审" : ($demondInfo['examine_type'] == 2 ? "终审" : "预审");//echo substr($demondInfo['file1'],0,-1);die;
        $this->assign([
            'examineTitle' => $examTitle,
            'demondInfo' => $demondInfo,
            'examineInfo' => $examineInfo,
            'role' => $this->roleId,
            'userId' => $this->userId,
          'file1'=>!empty($demondInfo['file1'])?explode(',',substr($demondInfo['file1'],0,-1)):'',
          'file2'=>!empty($demondInfo['file2'])?explode(',',substr($demondInfo['file2'],0,-1)):'',
          'file3'=>!empty($demondInfo['file3'])?explode(',',substr($demondInfo['file3'],0,-1)):'',
          'file4'=>!empty($demondInfo['file4'])?explode(',',substr($demondInfo['file4'],0,-1)):'',
        ]);
        return $this->fetch();
    }

    // 审核页面跳转
    public function examineBidView($bidId = 0)
    {
        //审核情况
        $examineInfo = Db::name("bid_examine")->where(['bid_id' => $bidId])->order("created_at desc")->find();

        $this->assign([
            'demondInfo' => $this->getBidDetail($bidId),
            'examineInfo' => $examineInfo,
            'roleName' => $this->roleName,
            'roleId' => $this->roleId,
        ]);

        return $this->fetch();
    }

    public function getBidDetail($bidId = 0)
    {
        $demondInfo = Db::name('bid')
            ->where(['a.id' => $bidId])
            ->alias('a')
            ->order('created_at desc')
            ->field("a.*")
            ->find();

        if (isset($demondInfo)) {
            $demondInfo['enrol_start_time'] = date('Y-m-d', $demondInfo['enrol_start_time']);
            $demondInfo['enrol_end_time'] = date('Y-m-d', $demondInfo['enrol_end_time']);
            $demondInfo['saudit_end_time'] = date('Y-m-d', $demondInfo['saudit_end_time']);
            $demondInfo['bid_qual_etime'] = date('Y-m-d', $demondInfo['bid_qual_etime']);
            $demondInfo['auction_etime'] = date('Y-m-d', $demondInfo['auction_etime']);
            $demondInfo['attachment_first_time'] = $demondInfo['attachment_first_time'] > 0 ? date('Y-m-d', $demondInfo['attachment_first_time']) : "";
            $demondInfo['attachment_second_time'] = $demondInfo['attachment_second_time'] > 0 ? date('Y-m-d', $demondInfo['attachment_second_time']) : "";
        }
        return $demondInfo;
    }

    public function bidExamine()
    {
        if (!in_array($this->roleId, [1, 3, 8])) {
            return false;
        }

        foreach ($this->params as $k => $v) {
            if ($k != 'bid') {
                if ($v == '') {
                    $this->apiReturn('200', "请填写审核信息完整！", []);
                }
            }
        }

        if ($this->roleId == 1) {
            $jingBefore = Db::name("bid_examine")->where(['bid_id' => $this->params['bid_id']])->find();
            if ($jingBefore['jing_before_examine_status'] != 0) {
                $this->apiReturn('200', "该审核已操作，请勿重新操作！", []);
            }
            if ($this->params['jing_before_examine_reason'] == '请输入审核意见') {
                $this->params['jing_before_examine_reason'] = '';
            }
            $examineInfo = [
                'bid_id' => $this->params['bid_id'],
                'jing_before_id' => $this->userId,
                'jing_before_examine_status' => $this->params['jing_before_examine_status'],
                'jing_before_time' => time(),
                'jing_before_examine_reason' => $this->params['jing_before_examine_reason'],
            ];
            if (empty($jingBefore)) {
                $res = Db::name("bid_examine")->insert($examineInfo);
            } else {
                $res = Db::name("bid_examine")->where(['bid_id' => $this->params['bid_id']])->update($examineInfo);
            }
            $bidStatus = 1;
            if ($this->params['jing_before_examine_status'] == 2) {//已驳回 中止了
                $bidStatus = 3;
            }
            Db::name("bid")->where(['id' => $this->params['bid_id']])->update(['status' => $bidStatus]);
            if ($res) $this->apiReturn('100', "已提交审核！", []);
        }


        if ($this->roleId == 8) {//经管办
            $examine = Db::name("bid_examine")->where(['bid_id' => $this->params['bid_id']])->find();
            if ($examine['jing_before_examine_status'] == 0) {
                $this->apiReturn('200', "镇经管办还未审核，请稍后再审核", []);
            }
            if ($examine['management_examine_status'] != 0) {
                $this->apiReturn('200', "该审核已操作，请勿重新操作！", []);
            }
            if ($this->params['management_examine_reason'] == '请输入审核意见') {
                $this->params['management_examine_reason'] = '';
            }
            $examineInfo = [
                'management_id' => $this->userId,
                'management_examine_status' => $this->params['management_examine_status'],
                'management_time' => time(),
                'management_examine_reason' => $this->params['management_examine_reason'],
            ];
            $res8 = Db::name("bid_examine")->where(['bid_id' => $this->params['bid_id']])->update($examineInfo);
            $bidStatus = 1;
            if ($this->params['management_examine_status'] == 2) {//已驳回 中止了
                $bidStatus = 3;
            }
            Db::name("bid")->where(['id' => $this->params['bid_id']])->update(['status' => $bidStatus]);
            if ($res8) $this->apiReturn('100', "已提交审核", []);
        }

        if ($this->roleId == 3) {//农经站
            $examine = Db::name("bid_examine")->where(['bid_id' => $this->params['bid_id']])->find();
            if ($examine['jing_before_examine_status'] == 0 || $examine['management_examine_status'] == 0) {
                $this->apiReturn('200', "镇经管办预审/经管办 还未审核，请稍后再审核", []);
            }
            if ($examine['farmer_examine_status'] != 0) {
                $this->apiReturn('200', "该审核已操作，请勿重新操作！", []);
            }
            if ($this->params['farmer_examine_reason'] == '请输入审核意见') {
                $this->params['management_examine_reason'] = '';
            }
            $examineInfo = [
                'farmer_id' => $this->userId,
                'farmer_examine_status' => $this->params['farmer_examine_status'],
                'farmer_time' => time(),
                'farmer_examine_reason' => $this->params['farmer_examine_reason'],
            ];
            $res3 = Db::name("bid_examine")->where(['bid_id' => $this->params['bid_id']])->update($examineInfo);
            $bidStatus = 2; //农经站 审核完成 更新bid状态 已审核
            if ($this->params['farmer_examine_status'] == 2) {//已驳回 中止了
                $bidStatus = 3;
            }
            Db::name("bid")->where(['id' => $this->params['bid_id']])->update(['status' => $bidStatus]);
            if ($res3) $this->apiReturn('100', "已提交审核", []);
        }

        $this->apiReturn('100', "审核失败，请重新操作！", []);
    }

    public function uploadBidAttach()
    {
        $attach = $this->params['annex_address'];
        $bidId = $this->params['bid_id'];
        if ($attach == "") {
            $this->apiReturn('200', "附件信息不存在！", []);
        }
        $bidInfo = Db::name("bid")->where(["id" => $bidId])->find();
        if (empty($bidInfo)) {
            $this->apiReturn('200', "您的申请已不存在！", []);
        }
        if ($bidInfo['status'] == 2) {

            if($bidInfo['bidder_type']==1){  //企业
                $bidData['file1'] = $this->params['file1'];
                $bidData['file2'] = $this->params['file2'];
                $bidData['file3'] = $this->params['file3'];
                $bidData['file4'] = $this->params['file4'];
                $bidData['file5'] = $this->params['file5'];
            }else{    //个人
                $bidData['file1'] = $this->params['file_1'];
                $bidData['file2'] = $this->params['file_2'];
                $bidData['file3'] = $this->params['file_3'];
                $bidData['file4'] = $this->params['file_4'];
                $bidData['file5'] = "";
            }

            if ($bidInfo['examine_type'] == 0) {
                $firstUploadData = ['attachment_first' => $attach, 'attachment_first_time' => time(), 'examine_type' => 1, 'status' => 1];
                $res = Db::name("bid")->where(['id' => $bidId])->update($firstUploadData);
                $res = Db::name("bid")->where(['id' => $bidId])->update($bidData);
                Db::name("bid_examine")->where(["bid_id" => $bidId])->delete();
                $this->apiReturn('100', "您的附件已提交！", []);
            }
            if ($bidInfo['examine_type'] == 1) {
                $firstUploadData = ['attachment_second' => $attach, 'attachment_second_time' => time(), 'examine_type' => 2, 'status' => 1];
                $res = Db::name("bid")->where(['id' => $bidId])->update($firstUploadData);
                $res = Db::name("bid")->where(['id' => $bidId])->update($bidData);
                Db::name("bid_examine")->where(["bid_id" => $bidId])->delete();
                $this->apiReturn('100', "您的附件已提交！", []);
            }
        }
        $this->apiReturn('200', "提交附件失败，请核实后在操作！", []);
    }

    public function getAjaxBidDetail()
    {
        $bidId = $this->params['id'];
        $this->apiReturn('200', "ok", ["bidInfo" => $this->getBidDetail($bidId)]);
    }

    //单图片上传接口;
    public function uploadimg(){

        $file = request()->file('file');
        // 移动到框架应用根目录/public/uploads/ 目录下
        if($file){
            $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads');
            if($info){
                $this->apiReturn('200', "ok", ["msg" =>'/uploads/'.$info->getSaveName()]);
                //return json_encode(['code'=>1,'msg'=>'/public/uploads/'.$info->getSaveName()]);

            }else{

                $this->apiReturn(100,$info->getError());

            }
        }
    }


}