<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/19
 * Time: 15:52
 */

namespace app\index\controller;

use think\Db;
use think\facade\Config;
use app\index\model\UserNotice;

/**
 * 首页
 * Class Index
 * @package app\wap\controller
 */
class Index extends Base
{
    public $news;
    public $userNotice;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->news = Db::table('ecshecom_portal_post');
        $this->userNotice = model('index/UserNotice');
    }

    /**
     * 首页
     */
    public function index($status = '', $countryid = '', $type = '', $name = '', $person = '', $start_time = "", $end_time = "")
    {

        //当前所有村企业
        $userRoleId = Db::name("user_role")->where(["role_id" => 0])->value("id");
        $allCountryInfo = Db::name("user")->where(["role_id" => $userRoleId])->field("id,username")->select();
        $this->assign([
            'allCountryInfo' => $allCountryInfo,
            'status' => $status,
            'countryid' => $countryid,
            'type' => $type,
            'name' => $name,
            'person' => $person,
            'start_time' => $start_time,
            'end_time' => $end_time,
        ]);

        //赛选条件
        $specWhere = array();
        if ($status != '') {
            $specWhere[] = ["a.status", 'eq', $status];
        }
        if ($countryid != '') {
            $specWhere[] = ["a.user_id", 'eq', $countryid];
        }
        if ($type != '') {
            if ($type == 1) {
                $specWhere[] = ["a.process_type", 'eq', 0];
                $specWhere[] = ["a.is_soft_first", 'eq', 1];
            }
            if ($type == 2) {
                $specWhere[] = ["a.process_type", 'eq', 0];
                $specWhere[] = ["a.is_soft_first", 'eq', 0];
            }
            if ($type == 3) {
                $specWhere[] = ["a.process_type", 'eq', 1];
                $specWhere[] = ["a.is_soft_first", 'eq', 1];
            }
            if ($type == 4) {
                $specWhere[] = ["a.process_type", 'eq', 1];
                $specWhere[] = ["a.is_soft_first", 'eq', 0];
            }
        }
        if ($name != '') {
            $specWhere[] = ["d.house_name", "like", "%" . $name . "%"];
        }
        if ($person != '') {
            $specWhere[] = ["d.original_tenant", "like", "%" . $person . "%"];
        }
        if (!empty($start_time)){
            $specWhere[] = ["a.created_at", '>', strtotime($start_time)];
        }
        if (!empty($end_time)){
            $specWhere[] = ["a.created_at", '<', strtotime($end_time)];
        }

        /**
         * 根据用户角色跳转页面
         * */
        if ($this->roleId == 0) //村企业
        {
            //当前用户发布的申请
            $demondInfos = Db::name('apple')
                ->where(['a.user_id' => $this->userId])
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('a.updated_at asc')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->paginate(30, false, ['query' => request()->param()]);

            $page = $demondInfos->render();

            //用户消息
            $demondIds = array();
            if (count($demondInfos) > 0) {
                for ($a = 0; $a < count($demondInfos); $a++) {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }
            $notices = $this->userNotice->where('apple_id', 'in', $demondIds)->order("created_at desc")->limit(10)->select();

            $this->assign([
                'notices' => $notices,
                'page' => $page,
                'demondInfos' => $demondInfos,
            ]);

            if (isMobile()) {
                return $this->fetch("index_mobile_finance");
            } else {
                return $this->fetch("index_finance");
            }
        }

        if ($this->roleId == 1) //镇经管办预审
        {

            //当前用户发布需审核的申请
            $demondInfos = Db::name('apple')
                //->where(['a.status' => 0, 'd.status' => 0]) //待审核
                //->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();

            //镇经管办预审只需要知道有哪些新的审核提交
            $demondIds = array();
            if (count($demondInfos) > 0) {
                for ($a = 0; $a < count($demondInfos); $a++) {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }
            $notices = $this->userNotice
                ->where('n.apple_id', 'in', $demondIds)
                ->alias('n')
                ->join('user u', 'u.id = n.user_id')
                ->field('n.*,u.username')
                ->order("n.created_at desc")
                ->limit(10)
                ->select();

            $this->assign([
                'notices' => $notices,
                'demondInfos' => $demondInfos,
            ]);

            if (isMobile()) {
                return $this->fetch("index_mobile_jing_before_examine");
            } else {
                return $this->fetch("index_jing_before_examine");
            }

        }

        if ($this->roleId == 7) //安全办前置
        {
            //1.简易流程，但是需要安全办安全预审的申请
            $demondInfos = Db::name('apple')
                ->where(['a.status' => 1, 'd.status' => 1, 'a.process_type' => 1, 'a.is_soft_first' => 1, 'e.security_examine_status' => 0, 'e.status' => 1]) //审核中,简易流程但需要前置审核
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e', 'a.id = e.apple_id')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();

            //2.常规流程.需要安全办前置审核
            $demondInfos1 = Db::name('apple')
                ->where(['a.status' => 1, 'd.status' => 1, 'a.process_type' => 0, 'a.is_soft_first' => 1, 'e.security_examine_status' => 0, 'e.status' => 1]) //常规流程
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e', 'a.id = e.apple_id')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();

            $demondInfos = array_merge($demondInfos, $demondInfos1);

            ////安全办只需要知道自己将要审核的申请相关的通知
            $demondIds = array();
            if (count($demondInfos) > 0) {
                for ($a = 0; $a < count($demondInfos); $a++) {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }
            $notices = $this->userNotice
                ->where('n.apple_id', 'in', $demondIds)
                ->alias('n')
                ->join('user u', 'u.id = n.user_id')
                ->field('n.*,u.username')
                ->order("n.created_at desc")
                ->limit(10)
                ->select();

            $this->assign([
                'notices' => $notices,
                'demondInfos' => $demondInfos,
            ]);

            if (isMobile()) {
                return $this->fetch("index_mobile_security_examine");
            } else {
                return $this->fetch("index_security_examine");
            }

        }

        /**
         * //2：镇经发办 3：农经站 4：审计办 5：财政所 6：镇资产公司,10：安全办，通用审核，无先后顺序
         * */
        if ($this->roleId == 2 || $this->roleId == 3 || $this->roleId == 4 || $this->roleId == 5 || $this->roleId == 6 || $this->roleId == 10) {
            //1.常规流程,需要安全预审，在6个部门审核
            $commonWhere['a.status'] = 1;
            $commonWhere['d.status'] = 1;
            $commonWhere['a.process_type'] = 0;
            $commonWhere['a.is_soft_first'] = 1; //需要安全预审
            $commonWhere['e.status'] = 1;
            $commonWhere['e.security_examine_status'] = 1; //安全预审已通过
            if ($this->roleId == 2) {
                $commonWhere['e.jing_examine_status'] = 0;
            }//2：镇经发办
            if ($this->roleId == 3) {
                $commonWhere['e.farmer_examine_status'] = 0;
            }//3：农经站
            if ($this->roleId == 4) {
                $commonWhere['e.audit_examine_status'] = 0;
            }//4：审计办
            if ($this->roleId == 5) {
                $commonWhere['e.finance_examine_status'] = 0;
            }//5：财政所
            if ($this->roleId == 6) {
                $commonWhere['e.assets_examine_status'] = 0;
            }//6：镇资产公司
            if ($this->roleId == 10) {
                $commonWhere['e.security_do_examine_status'] = 0;
            }//6：安全办
            $demondInfos = Db::name('apple')
                ->where($commonWhere) //常规流程
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e', 'a.id = e.apple_id')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();

            //2.常规流程,不需要安全预审，不先后顺序
            $commonWhere1['a.status'] = 1;
            $commonWhere1['d.status'] = 1;
            $commonWhere1['a.process_type'] = 0;
            $commonWhere1['a.is_soft_first'] = 0; //不需要安全预审
            $commonWhere1['e.status'] = 1;
            if ($this->roleId == 2) {
                $commonWhere1['e.jing_examine_status'] = 0;
            }//2：镇经发办
            if ($this->roleId == 3) {
                $commonWhere1['e.farmer_examine_status'] = 0;
            }//3：农经站
            if ($this->roleId == 4) {
                $commonWhere1['e.audit_examine_status'] = 0;
            }//4：审计办
            if ($this->roleId == 5) {
                $commonWhere1['e.finance_examine_status'] = 0;
            }//5：财政所
            if ($this->roleId == 6) {
                $commonWhere1['e.assets_examine_status'] = 0;
            }//6：镇资产公司
            if ($this->roleId == 10) {
                $commonWhere1['e.security_do_examine_status'] = 0;
            }//6：安全办
            $demondInfos1 = Db::name('apple')
                ->where($commonWhere1) //常规流程
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e', 'a.id = e.apple_id')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();

            $demondInfos = array_merge($demondInfos, $demondInfos1);

            ////其它5个部门只需要知道自己将要审核的申请相关的通知
            $demondIds = array();
            if (count($demondInfos) > 0) {
                for ($a = 0; $a < count($demondInfos); $a++) {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }

            $notices = $this->userNotice
                ->where('n.apple_id', 'in', $demondIds)
                ->alias('n')
                ->join('user u', 'u.id = n.user_id')
                ->field('n.*,u.username')
                ->order("n.created_at desc")
                ->limit(10)
                ->select();

            $this->assign([
                'notices' => $notices,
                'demondInfos' => $demondInfos,
            ]);

            if (isMobile()) {
                return $this->fetch("index_mobile_common_examine");
            } else {
                return $this->fetch("index_common_examine");
            }

        }

        if ($this->roleId == 8) //经管办
        {
          $commonWhere = [];
          $commonWhere1 = [];
          $commonWhere2 = [];
            //1.常规流程,6部门都已审核
            //$commonWhere['a.status'] = 1;
            //$commonWhere['d.status'] = 1;
            //$commonWhere['a.process_type'] = 0;
            //$commonWhere['e.status'] = 1;
            //$commonWhere['e.security_examine_status'] =1; //安全预审已通过
            //$commonWhere['e.security_do_examine_status'] = 1;
            //$commonWhere['e.jing_examine_status'] = 1;
            //$commonWhere['e.farmer_examine_status'] = 1;
            //$commonWhere['e.audit_examine_status'] = 1;
            //$commonWhere['e.finance_examine_status'] = 1;
            //$commonWhere['e.assets_examine_status'] = 1;
            //$commonWhere['e.management_examine_status'] = 0;
            $demondInfos = Db::name('apple')
                ->where($commonWhere) //常规流程
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e', 'a.id = e.apple_id')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();

            //2.简约流程，需安全预审，
            $commonWhere1['a.status'] = 1;
            $commonWhere1['d.status'] = 1;
            $commonWhere1['a.process_type'] = 1;
            $commonWhere1['a.is_soft_first'] = 1; //需要安全预审
            $commonWhere1['e.status'] = 1;
            $commonWhere1['e.security_examine_status'] = 1; //安全预审已通过
            $commonWhere1['e.management_examine_status'] = 0;
            $demondInfos1 = Db::name('apple')
                ->where($commonWhere1) //常规流程
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e', 'a.id = e.apple_id')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();

            //3.简约流程，无需安全预审，
            $commonWhere2['a.status'] = 1;
            $commonWhere2['d.status'] = 1;
            $commonWhere2['a.process_type'] = 1;
            $commonWhere2['a.is_soft_first'] = 0; //不需要安全预审
            $commonWhere2['e.status'] = 1;
            $commonWhere2['e.management_examine_status'] = 0;
            $demondInfos2 = Db::name('apple')
                ->where($commonWhere2) //常规流程
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e', 'a.id = e.apple_id')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();//var_dump($demon$demondInfos2dInfos);die;

            $demondInfos = array_merge($demondInfos, $demondInfos1);
            $demondInfos = array_merge($demondInfos, $demondInfos2);

            ////安全办只需要知道自己将要审核的申请相关的通知
            $demondIds = array();
            if (count($demondInfos) > 0) {
                for ($a = 0; $a < count($demondInfos); $a++) {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }
            $notices = $this->userNotice
                ->where('n.apple_id', 'in', $demondIds)
                ->alias('n')
                ->join('user u', 'u.id = n.user_id')
                ->field('n.*,u.username')
                ->order("n.created_at desc")
                ->limit(10)
                ->select();

            $this->assign([
                'notices' => $notices,
                'demondInfos' => $demondInfos,
            ]);

            if (isMobile()) {
                return $this->fetch("index_mobile_management_examine");
            } else {
                return $this->fetch("index_management_examine");
            }
        }

        if ($this->roleId == 9) //镇领导
        {
            //1.常规流程,经管办已审核
            $commonWhere['a.status'] = 1;
            $commonWhere['d.status'] = 1;
            $commonWhere['a.process_type'] = 0;
            $commonWhere['e.status'] = 1;
            $commonWhere['e.management_examine_status'] = 1; //经管办已审核
            $commonWhere['e.town_examine_status'] = 0;
            $demondInfos = Db::name('apple')
                ->where($commonWhere) //常规流程
                ->where($specWhere)
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e', 'a.id = e.apple_id')
                ->join('apple_details d', 'a.id = d.apple_id')
                ->field("d.*,a.updated_at as apple_updated_at,a.created_at as apple_created_at,a.contract_type as apple_contract_type,a.process_type as apple_process_type,a.is_soft_first as apple_is_soft_first,a.is_public_rental as apple_is_public_rental,a.status as apple_status")
                ->select();

            ////安全办只需要知道自己将要审核的申请相关的通知
            $demondIds = array();
            if (count($demondInfos) > 0) {
                for ($a = 0; $a < count($demondInfos); $a++) {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }
            $notices = $this->userNotice
                ->where('n.apple_id', 'in', $demondIds)
                ->alias('n')
                ->join('user u', 'u.id = n.user_id')
                ->field('n.*,u.username')
                ->order("n.created_at desc")
                ->limit(10)
                ->select();

            $this->assign([
                'notices' => $notices,
                'demondInfos' => $demondInfos,
            ]);

            if (isMobile()) {
                return $this->fetch("index_mobile_town_examine");
            } else {
                return $this->fetch("index_town_examine");
            }
        }

        return;
    }
}