<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/19
 * Time: 15:52
 */
namespace app\index\controller;

use app\index\model\UserNotice;
use think\Db;

/**
 * 用户中心
 * Class Index
 * @package app\wap\controller
 */
class News extends Base
{

    public $user;
    public $userNotice;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->user = model('index/User');
        $this->userNotice = model('index/UserNotice');
    }

    /**
     * 消息列表
     */
    public function lst(){

        //判断是否有未读数据
        if(UserNotice::where(['user_id'=>$this->userId,'status'=>0])->find())
        {
            UserNotice::where(['user_id'=>$this->userId,'status'=>0])->update(['status' => 1]);
        }
        /**
         * 根据用户角色跳转页面
         * */
        if($this->roleId == 0) //村企业
        {
            //当前用户发布的申请
            $demondInfos = Db::name('apple')
                ->where(['a.user_id'=>$this->userId])
                ->alias('a')
                ->group('d.apple_id')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            //用户消息
            $demondIds = array();
            if(count($demondInfos) > 0)
            {
                for ($a=0;$a<count($demondInfos);$a++)
                {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }

            $notices = $this->userNotice->where('apple_id','in',$demondIds)->order('created_at desc')->paginate(20);
            $page = $notices->render();

            $this->assign([
                'notices' => $notices,
                'page' => $page,
            ]);

            return $this->fetch();
        }

        /**
         * 根据用户角色跳转页面
         * */
        if($this->roleId == 1) //镇经管办预审
        {
            //当前用户发布需审核的申请
            $demondInfos = Db::name('apple')
                ->where(['a.status'=>0,'d.status'=>0]) //待审核
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            //镇经管办预审只需要知道有哪些新的审核提交
            $demondIds = array();
            if(count($demondInfos) > 0)
            {
                for ($a=0;$a<count($demondInfos);$a++)
                {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }

            $notices = $this->userNotice
                            ->where('n.apple_id','in',$demondIds)
                            ->alias('n')
                            ->join('user u','u.id = n.user_id')
                            ->order('n.created_at desc')
                            ->field('n.*,u.username')
                            ->paginate(20);

            $page = $notices->render();

            $this->assign([
                'notices' => $notices,
                'page' => $page,
            ]);

            return $this->fetch('lst_jing_before_examine');
        }

        /**
         * 根据用户角色跳转页面
         * */
        if($this->roleId == 7) //安全办
        {
            //1.简易流程，但是需要安全办安全预审的申请
            $demondInfos = Db::name('apple')
                ->where(['a.status'=>1,'d.status'=>1,'process_type'=>1,'is_soft_first'=>1]) //审核中,简易流程但需要前置审核
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            //2.常规流程
            $demondInfos1 = Db::name('apple')
                ->where(['a.status'=>1,'d.status'=>1,'process_type'=>0,'is_soft_first'=>1]) //常规流程
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            $demondInfos = array_merge($demondInfos,$demondInfos1);

            //镇经管办预审只需要知道有哪些新的审核提交
            $demondIds = array();
            if(count($demondInfos) > 0)
            {
                for ($a=0;$a<count($demondInfos);$a++)
                {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }

            $notices = $this->userNotice
                ->where('n.apple_id','in',$demondIds)
                ->alias('n')
                ->join('user u','u.id = n.user_id')
                ->order('n.created_at desc')
                ->field('n.*,u.username')
                ->paginate(20);

            $page = $notices->render();

            $this->assign([
                'notices' => $notices,
                'page' => $page,
            ]);

            return $this->fetch('lst_jing_before_examine');
        }

        /**
         * //2：镇经发办 3：农经站 4：审计办 5：财政所 6：镇资产公司 10：安全办，通用审核，无先后顺序
         * */
        if($this->roleId == 2 || $this->roleId == 3 || $this->roleId == 4 || $this->roleId == 5 || $this->roleId == 6 || $this->roleId == 10)
        {

            $commonWhere['a.status'] = 1;
            $commonWhere['d.status'] = 1;
            $commonWhere['a.process_type'] = 0;

            //1.常规流程,其它5个部门只需要审核常规流程的申请
            $demondInfos = Db::name('apple')
                ->where($commonWhere) //常规流程
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e','a.id = e.apple_id')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            ////其它5个部门只需要知道自己将要审核的申请相关的通知
            $demondIds = array();
            if(count($demondInfos) > 0)
            {
                for ($a=0;$a<count($demondInfos);$a++)
                {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }

            $notices = $this->userNotice
                ->where('n.apple_id','in',$demondIds)
                ->alias('n')
                ->join('user u','u.id = n.user_id')
                ->order('n.created_at desc')
                ->field('n.*,u.username')
                ->paginate(20);

            $page = $notices->render();

            $this->assign([
                'notices' => $notices,
                'page' => $page,
            ]);

            return $this->fetch('lst_jing_before_examine');
        }

        if($this->roleId == 8) //经管办
        {
            //1.常规流程,6部门都已审核
            $commonWhere['a.status'] = 1;
            $commonWhere['d.status'] = 1;
            $commonWhere['a.process_type'] = 0;
            $commonWhere['e.status'] =1;
            $commonWhere['e.security_do_examine_status'] =1;
            $commonWhere['e.jing_examine_status'] = 1;
            $commonWhere['e.farmer_examine_status'] = 1;
            $commonWhere['e.audit_examine_status'] = 1;
            $commonWhere['e.finance_examine_status'] = 1;
            $commonWhere['e.assets_examine_status'] = 1;
            $demondInfos = Db::name('apple')
                ->where($commonWhere) //常规流程
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e','a.id = e.apple_id')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            //2.简约流程，需安全预审，
            $commonWhere1['a.status'] = 1;
            $commonWhere1['d.status'] = 1;
            $commonWhere1['a.process_type'] = 1;
            $commonWhere1['a.is_soft_first'] = 1; //需要安全预审
            $commonWhere1['e.status'] =1;
            $commonWhere1['e.security_examine_status'] =1; //安全预审已通过
            $demondInfos1 = Db::name('apple')
                ->where($commonWhere1) //常规流程
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e','a.id = e.apple_id')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            //3.简约流程，无需安全预审，
            $commonWhere2['a.status'] = 1;
            $commonWhere2['d.status'] = 1;
            $commonWhere2['a.process_type'] = 1;
            $commonWhere2['a.is_soft_first'] = 0; //不需要安全预审
            $commonWhere2['e.status'] =1;
            $demondInfos2 = Db::name('apple')
                ->where($commonWhere2) //常规流程
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e','a.id = e.apple_id')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            $demondInfos = array_merge($demondInfos,$demondInfos1);
            $demondInfos = array_merge($demondInfos,$demondInfos2);

            ////安全办只需要知道自己将要审核的申请相关的通知
            $demondIds = array();
            if(count($demondInfos) > 0)
            {
                for ($a=0;$a<count($demondInfos);$a++)
                {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }

            $notices = $this->userNotice
                ->where('n.apple_id','in',$demondIds)
                ->alias('n')
                ->join('user u','u.id = n.user_id')
                ->order('n.created_at desc')
                ->field('n.*,u.username')
                ->paginate(20);

            $page = $notices->render();

            $this->assign([
                'notices' => $notices,
                'page' => $page,
            ]);

            return $this->fetch('lst_jing_before_examine');
        }

        if($this->roleId == 9) //镇领导
        {
            //1.常规流程
            $commonWhere['a.status'] = 1;
            $commonWhere['d.status'] = 1;
            $commonWhere['a.process_type'] = 0;
            $commonWhere['e.status'] =1;
            $demondInfos = Db::name('apple')
                ->where($commonWhere) //常规流程
                ->alias('a')
                ->group('d.apple_id')
                ->order('d.created_at desc')
                ->join('examine e','a.id = e.apple_id')
                ->join('apple_details d','a.id = d.apple_id')
                ->field("d.apple_id")
                ->select();

            ////安全办只需要知道自己将要审核的申请相关的通知
            $demondIds = array();
            if(count($demondInfos) > 0)
            {
                for ($a=0;$a<count($demondInfos);$a++)
                {
                    $demondIds[$a] = $demondInfos[$a]['apple_id'];
                }
            }

            $notices = $this->userNotice
                ->where('n.apple_id','in',$demondIds)
                ->alias('n')
                ->join('user u','u.id = n.user_id')
                ->order('n.created_at desc')
                ->field('n.*,u.username')
                ->paginate(20);

            $page = $notices->render();

            $this->assign([
                'notices' => $notices,
                'page' => $page,
            ]);

            return $this->fetch('lst_jing_before_examine');
        }

        return;
    }

}